# Generated by Django 5.0.2 on 2024-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_useractivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='created_through_api',
            field=models.BooleanField(default=False),
        ),
    ]
