# Generated by Django 5.0.2 on 2024-02-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_useractivation_created_through_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestausuario',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='respuestausuario',
            name='pregunta_respuesta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.preguntarespuesta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestausuario',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.encuesta'),
        ),
    ]
